# -*- coding: utf-8 -*-
"""
/***************************************************************************
 traindata_generator
                                 A QGIS plugin
 This plugin developed mainly for converting geospatial tiff data to deep learning training sets
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-10-10
        copyright            : (C) 2020 by vk
        email                : vk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load traindata_generator class from file traindata_generator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tiff_2_train import traindata_generator
    return traindata_generator(iface)
